### ISSUE TITLE
[Feature] - Add support for Hoverpack Extensions Redux.

### ISSUE THREAD

**Issue by tpill90** [derpierre65/SatisfactoryMods#1]
Hi,  would it be possible to add support for toggling between the `Hover Pack MK2`  added by the [Hover Pack Extensions Redux](https://ficsit.app/mod/HoverPackExtensionsRedux)?  

This mod is great, it was exactly what I'm looking for.  I just also love having the extra range of the MK2 pack and would like to have the easy toggle for it.

**Comment by derpierre65** [comment]
i think that should be possible, i can check it in the coming week

**Comment by tpill90** [comment]
Very cool. Thank you so much!

**Comment by PoloBello** [comment]
Hi there, and thank you for this very useful mod.
Like tpill90, I'd like to use it with a MK2 mod : https://ficsit.app/mod/EquipmentMk2
Do you think you could update it to work with it too ? 

Have a nice day !

**Comment by derpierre65** [comment]
mods are supported in 1.1, works with EquipemntMK2 and Hover Pack Extensions Redux

**Comment by PoloBello** [comment]
Thank you very much : )

**Comment by tpill90** [comment]
Works perfectly!  Thank you so much!
