### ISSUE TITLE
Togglepack mod support not working?

### ISSUE THREAD

**Issue by UltraJohn** [derpierre65/SatisfactoryMods#2]
Hey there, in the 1.1.0 update it states it supports modded jetpacks/hoverpacks, but I don't see any option ingame to enable it? I'm using the mod Progressive Hover Pack and I'm not able to make it switch to any of those.

**Comment by derpierre65** [comment]
i can check the mod later
you don't need to enable an option, the mod search an available hoverpack in your inventory
if the mod don't use the default hoverpack as base then the current solution does not work

**Comment by derpierre65** [comment]
Progressive Hover Pack now supported in 1.1.1

**Comment by UltraJohn** [comment]
Just tried it out, and it seems to randomly stop working. If I manually swap between the hoverpack/jetpack it starts working for a bit, until it randomly stops working again.

**Comment by derpierre65** [comment]
i think you run into the issue that i had while playing with the mod
sometime the keybinding stops working
idk why that's happen, maybe i did something wrong, i need to check why this happen and a way to reproduce it.
